name: Build and Sign AAB

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
          node-version: 18

    - name: Install dependencies
      run: |
          yarn install

    - name: Build AAB
      run: |
        ./gradlew bundleRelease
      working-directory: android  

    - name: Sign AAB
      run: |
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore /home/shruti/codepush/android/app/your_key_name.keystore -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }} -signedjar app-release-signed.aab app-release.aab alias_name
      working-directory: android/app/build/outputs/bundle/release  

    - name: Zipalign AAB
      run: |
        $ANDROID_HOME/build-tools/32.0.0/zipalign -v -p 4 app-release-unsigned.apk app-release-unsigned-aligned.apk
      env:
        ANDROID_HOME: ${{ runner.workspace }}/android/sdk  
      working-directory: android/app/build/outputs/bundle/release  

    - name: Upload AAB artifact
      uses: actions/upload-artifact@v2
      with:
        name: signed-aab
        path: android/app/build/outputs/bundle/release/app-release-unsigned-aligned.apk  
